# Generated by Django 4.1.7 on 2023-04-10 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('real-estate', 'real-estate'), ('vehicles', 'vehicles'), ('event-supplies', 'event-supplies'), ('fashion', 'fashion'), ('recreational', 'recreational'), ('sports', 'sports'), ('electronics', 'electronics')], max_length=64)),
                ('rate', models.CharField(max_length=128)),
                ('lease_term', models.CharField(max_length=255)),
                ('lease_cost', models.CharField(max_length=128)),
                ('image1', models.URLField()),
                ('image2', models.URLField()),
                ('image3', models.URLField()),
                ('image4', models.URLField()),
                ('image5', models.URLField()),
                ('image6', models.URLField(blank=True, null=True)),
                ('image7', models.URLField(blank=True, null=True)),
                ('image8', models.URLField(blank=True, null=True)),
                ('image9', models.URLField(blank=True, null=True)),
                ('image10', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
