# Generated by Django 4.1.10 on 2023-08-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='category',
            field=models.CharField(choices=[('real-estate', 'Real Estate'), ('vehicles', 'Vehicles'), ('event-supplies', 'Event Supplies'), ('fashion', 'Fashion'), ('recreational', 'Recreational'), ('sports', 'Sports'), ('electronics', 'Electronics')], max_length=64),
        ),
        migrations.AlterField(
            model_name='rental',
            name='image4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='image5',
            field=models.URLField(blank=True, null=True),
        ),
    ]
