# Generated by Django 4.1.7 on 2023-04-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rate',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='rental',
            name='total_lease_cost',
            field=models.CharField(max_length=128),
        ),
    ]
