# Generated by Django 4.1.7 on 2023-04-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_rental_rate_alter_rental_total_lease_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='total_lease_cost',
            new_name='lease_cost',
        ),
        migrations.AddField(
            model_name='rental',
            name='lease_term',
            field=models.CharField(default='2 months', max_length=255),
            preserve_default=False,
        ),
    ]
