# Generated by Django 4.1.10 on 2023-08-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_rental_category_alter_rental_image4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='lease_cost',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
