# Generated by Django 4.1.7 on 2023-04-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_rename_total_lease_cost_rental_lease_cost_and_more'),
    ]

    operations = [
    ]
