# Generated by Django 4.1.7 on 2023-04-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='user',
            name='bus_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
