# Generated by Django 4.1.7 on 2023-04-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ratings',
            field=models.ManyToManyField(blank=True, to='user.rating'),
        ),
    ]
