# Generated by Django 4.1.7 on 2023-04-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
