# Generated by Django 4.1.7 on 2023-04-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ratings',
        ),
    ]
