# Generated by Django 4.1.10 on 2023-08-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bus_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
