# Generated by Django 4.1.10 on 2023-09-28 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKyc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selfie_image', models.URLField()),
                ('id_front_image', models.URLField()),
                ('id_back_image', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
