# Generated by Django 4.1.10 on 2023-09-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userkyc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_kyc_verified',
        ),
    ]
