# Generated by Django 4.1.10 on 2023-09-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_is_verified_user_is_kyc_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_kyc_verified',
        ),
        migrations.AddField(
            model_name='userkyc',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
