# Generated by Django 4.1.7 on 2023-04-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_is_self_contain_alter_property_is_furnished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='agent',
            new_name='user',
        ),
    ]
